# Generated by Django 3.0.5 on 2020-04-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_client_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='importorder',
            name='TRID',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='importorder',
            name='count_place',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importorder',
            name='volume',
            field=models.FloatField(default=0),
        ),
    ]
