# Generated by Django 3.0.5 on 2020-04-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200415_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='passport',
            field=models.CharField(max_length=129, unique=True),
        ),
    ]
