# Generated by Django 3.0.5 on 2020-04-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200416_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientorder',
            name='price',
            field=models.FloatField(default=0, max_length=20),
        ),
    ]
