# Generated by Django 3.0.5 on 2020-04-30 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200419_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factoryitem',
            name='catalogue_num',
            field=models.CharField(max_length=24),
        ),
    ]
