# Generated by Django 3.0.5 on 2020-04-30 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200430_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='stock_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='orders.StockItem'),
            preserve_default=False,
        ),
    ]
