# Generated by Django 3.0.5 on 2020-05-01 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_movement_stock_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='importorder',
            name='wight',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='importorder',
            name='KW',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='movement',
            name='import_old',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='orders.ImportOrder'),
        ),
        migrations.DeleteModel(
            name='ImportItem',
        ),
    ]
