# Generated by Django 3.0.5 on 2020-05-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20200501_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('current_rate', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='stockitem',
            old_name='current_price',
            new_name='current_price_eur',
        ),
        migrations.RenameField(
            model_name='stockitem',
            old_name='last_price',
            new_name='current_price_ru',
        ),
        migrations.RemoveField(
            model_name='importimage',
            name='import_order',
        ),
        migrations.RemoveField(
            model_name='movement',
            name='import_old',
        ),
        migrations.AddField(
            model_name='stockitem',
            name='incorrect_factory',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='last_price_ru',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='last_prive_eur',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='stock_choices',
            field=models.CharField(choices=[('waiting for processing', 'Ждет обработки'), ('processed', 'Обработан'), ('in order', 'Заказан'), ('at exhibition', 'На выставке'), ('in stock', 'На складе'), ('sell', 'Продан'), ('cancel', 'Отмена')], default='waiting for processing', max_length=30),
        ),
        migrations.DeleteModel(
            name='ImportOrder',
        ),
    ]
