# Generated by Django 3.0.5 on 2020-05-01 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0009_auto_20200501_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_number', models.CharField(max_length=10, unique=True)),
                ('status', models.CharField(choices=[('processing', 'Обработка'), ('waiting for payment', 'Ждем предоплаты'), ('order to factory', 'Заказ изготовителю'), ('wait for ab', 'Ждем AB'), ('description for vaitek', 'Описание для VAITEK'), ('waiting payment from vitek', 'Ждем платежки от VAITEK'), ('in germany', 'В Германии'), ('in stock', 'У нас на складе'), ('ready to delivery', 'Готов к доставке'), ('delivery agreed', 'Доставка клиенту согласована'), ('awaiting assembly', 'Ожидает сборки'), ('act uploaded', 'Акт загружен'), ('done', 'Выполнен'), ('claim', 'Рекламация')], default='processing', max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('KW', models.CharField(blank=True, max_length=16)),
                ('delivery_to_client', models.DateField(auto_now_add=True)),
                ('AB_num', models.CharField(blank=True, max_length=32)),
                ('AB_file', models.ImageField(blank=True, upload_to='')),
                ('VAITEK_order', models.CharField(blank=True, max_length=128)),
                ('VAITEK_payment', models.ImageField(blank=True, upload_to='')),
                ('bill', models.ImageField(blank=True, upload_to='')),
                ('TTN', models.ImageField(blank=True, upload_to='')),
                ('TRID', models.CharField(blank=True, max_length=128)),
                ('count_place', models.IntegerField(default=0)),
                ('volume', models.FloatField(default=0)),
                ('wight', models.FloatField(default=0)),
                ('container_num', models.CharField(blank=True, max_length=10)),
                ('client_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_orders', to='orders.ClientOrder')),
                ('import_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ImportImage',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='client_order',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='factory_item',
        ),
        migrations.DeleteModel(
            name='Movement',
        ),
        migrations.DeleteModel(
            name='StockItem',
        ),
    ]
