# Generated by Django 3.0.5 on 2020-05-01 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_importimage_movement_stockitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='factory_item',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='orders.FactoryItem'),
        ),
    ]
