# Generated by Django 3.0.5 on 2020-05-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20200501_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Корректный'),
        ),
    ]
