# Generated by Django 3.0.5 on 2020-05-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20200501_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Отгружен'),
        ),
    ]
