# Generated by Django 3.0.5 on 2020-05-01 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20200501_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='is_ordered',
            field=models.BooleanField(default=False, verbose_name='Заказан'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='is_shipped',
            field=models.BooleanField(default=False, verbose_name='Отгружен'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Корректный'),
        ),
    ]
