# Generated by Django 3.0.5 on 2020-05-10 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20200501_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factorycollection',
            name='factory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='orders.Factory'),
        ),
    ]
