# Generated by Django 3.0.5 on 2020-05-10 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_auto_20200510_1150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factoryitem',
            old_name='catalogue_num',
            new_name='catalogue_number',
        ),
        migrations.RenameField(
            model_name='factoryitem',
            old_name='fac_collection',
            new_name='factory_collection',
        ),
    ]
