# Generated by Django 3.0.5 on 2020-05-10 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20200510_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movement',
            name='author',
        ),
        migrations.RemoveField(
            model_name='movement',
            name='import_old',
        ),
        migrations.RemoveField(
            model_name='movement',
            name='owner_old',
        ),
        migrations.RemoveField(
            model_name='movement',
            name='stock_item',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='client_order',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='factory_item',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='import_order',
        ),
        migrations.DeleteModel(
            name='FactoryItem',
        ),
        migrations.DeleteModel(
            name='Movement',
        ),
        migrations.DeleteModel(
            name='StockItem',
        ),
    ]
