# Generated by Django 3.0.5 on 2020-05-11 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_factoryitem_movement_stockitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockitem',
            old_name='last_prive_eur',
            new_name='last_price_eur',
        ),
    ]
