# Generated by Django 3.0.5 on 2020-05-18 17:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_auto_20200511_1957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='adress',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='clientorder',
            name='when_published',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
