# Generated by Django 3.0.5 on 2020-05-26 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_auto_20200518_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientorder',
            name='eur_rate',
        ),
    ]
