# Generated by Django 3.0.5 on 2020-05-26 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_remove_clientorder_eur_rate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CurrentPrice',
            new_name='CurrentRate',
        ),
    ]
