# Generated by Django 3.0.5 on 2020-06-04 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_clientorder_eur_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_data',
            new_name='payment_date',
        ),
    ]
