# Generated by Django 3.0.5 on 2020-06-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_auto_20200604_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='stock_choices',
            field=models.CharField(choices=[('waiting for processing', 'Ждет обработки'), ('processed', 'Обработан'), ('in order', 'Заказан'), ('at exhibition', 'На выставке'), ('in stock', 'На складе'), ('sell', 'Продан'), ('cancel', 'Отмена')], default='cancel', max_length=30),
        ),
    ]
