# Generated by Django 3.0.5 on 2020-06-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_auto_20200605_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='bank_euro_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='factor',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='factory_price_eur',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='importorder',
            name='import_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
