# Generated by Django 3.0.5 on 2020-06-06 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_auto_20200606_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importorder',
            name='client_order',
        ),
    ]
