# Generated by Django 3.0.5 on 2020-06-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_remove_importorder_client_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientorder',
            name='when_published',
            field=models.DateTimeField(),
        ),
    ]
