# Generated by Django 3.0.5 on 2020-06-08 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_auto_20200607_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importorder',
            name='delivery_to_client',
        ),
    ]
