# Generated by Django 3.0.5 on 2020-06-08 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_auto_20200608_2137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='importorder',
            old_name='count_place',
            new_name='amount_place',
        ),
    ]
