# Generated by Django 3.0.5 on 2020-06-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0035_auto_20200608_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='importorder',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
