# Generated by Django 3.0.5 on 2020-06-10 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0036_importorder_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientorder',
            name='when_published',
            field=models.DateTimeField(blank=True),
        ),
    ]
