# Generated by Django 3.0.5 on 2020-06-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0037_auto_20200610_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importorder',
            name='AB_file',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='importorder',
            name='TTN',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='importorder',
            name='VAITEK_payment',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='importorder',
            name='bill',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
