# Generated by Django 3.0.5 on 2020-06-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0038_auto_20200616_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factoryitem',
            name='description_de',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='factoryitem',
            name='description_rus',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
