# Generated by Django 3.0.5 on 2020-06-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0039_auto_20200621_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factoryitem',
            name='description_de',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='factoryitem',
            name='description_rus',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
