# Generated by Django 3.0.5 on 2020-06-21 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0040_auto_20200621_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factoryitem',
            name='factory_collection',
        ),
    ]
