# Generated by Django 3.0.5 on 2020-07-06 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0044_factoryitem_movement_stockitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='middle_name',
        ),
    ]
