# Generated by Django 3.0.5 on 2020-07-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0045_remove_client_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientorder',
            name='when_published',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
